spring:

  datasource:
    url: jdbc:postgresql://localhost/pokedex
    username: postgres
    password: 1234567

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true