spring:
  datasource:
    url: jdbc:postgresql://192.241.152.103:5432/pokedex?useSSL=true
    username: postgres
    password: 123456

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true